export const PAGE_SIZE = 100

export const FAKE_DATA = [
  {
    createdAt: '2026-03-29T10:42:43.349938',
    createdBy: 1,
    updatedAt: '2026-03-31T02:20:05.409457',
    updatedBy: 1,
    status: 'ACTIVE',
    createdUsername: 'Super Admin',
    updatedUsername: 'Super Admin',
    id: 3663,
    code: 'CS002111',
    name: '223213',
    vnName: 'ADSDSAD',
    website: 'dsdasdasdasda',
    picHandleAgent: null,
    clientStageId: 1,
    clientCategoryId: 3,
    countryId: null,
    clientStageName: 'NEW CUSTOMER1',
    clientCategoryName: 'FREEHAND',
    taxId: null,
    clientGroup: 'CUSTOMER',
    isPerson: false,
    emails: ['dsad@gmail.com'],
    arAddressId: 3506,
    apAddressId: 3506,
    arIsCreditApproved: true,
    arIsCreditHold: false,
    arIsBadDebt: false,
    apIsCreditHold: false,
    isAssociationMember: false,
    clientSalePersonNames: 'Nguyễn Thị Liên, Lê Vũ Hảo',
    associationName: null,
    clientStage: {
      createdAt: '2024-10-01T02:00:17.287897',
      createdBy: 1,
      updatedAt: '2025-12-31T04:33:45',
      updatedBy: 1,
      status: 'ACTIVE',
      createdUsername: 'Super Admin',
      updatedUsername: 'Super Admin',
      id: 1,
      code: '0NEW',
      name: 'NEW CUSTOMER1',
      displayPosition: 1,
      description: 'NEWLY ACQUIRED, NO SHIPMENT YET',
      isSystem: false,
    },
    clientCategory: {
      createdAt: '2024-10-01T01:59:36.690794',
      createdBy: 1,
      updatedAt: '2024-12-04T02:55:29.623997',
      updatedBy: 1,
      status: 'ACTIVE',
      createdUsername: 'Super Admin',
      updatedUsername: 'Super Admin',
      id: 3,
      code: 'FREEHAND',
      name: 'FREEHAND',
      displayPosition: 2,
      description: 'FREEHAND CUSTOMER',
      isSystem: false,
    },
    defaultAddress: {
      createdAt: '2026-03-29T10:42:43.358544',
      createdBy: 1,
      updatedAt: '2026-03-30T10:42:02.936746',
      updatedBy: 1,
      status: 'ACTIVE',
      createdUsername: 'Super Admin',
      updatedUsername: 'Super Admin',
      id: 3506,
      code: 'CS002111-ADD',
      name: '223213',
      taxId: null,
      fullAddress: 'DSADASSADSADSAD',
      vnFullAddress: 'DSAD',
      email: null,
      fax: 'dsadas',
      telephone: 'dsada',
      ext: 'dsadas',
      startWorkingHour: null,
      endWorkingHour: null,
      isDefault: true,
      workingDays: [],
      clientId: 3663,
      countryId: 3,
      countryName: 'Albania',
      country: {
        id: 3,
        code: 'AL',
        name: 'Albania',
        phoneCountryCode: '+355\n',
        subdivisionType: 'NOTHING',
        displayPosition: null,
      },
      client: null,
      branchAddressCapabilities: null,
      branchAddressCapabilityIds: null,
      defaultContact: {
        createdAt: '2026-03-29T10:42:43.360166',
        createdBy: 1,
        updatedAt: '2026-04-01T16:02:37.96141',
        updatedBy: 1,
        status: 'ACTIVE',
        createdUsername: 'Super Admin',
        updatedUsername: 'Super Admin',
        id: 4103,
        name: 'dsa',
        gender: 'FEMALE',
        birthdate: '2026-03-30',
        mobilePhone: '321321312321232342323',
        telephone: '23213423434324345435235345454545435435454',
        email: 'sadasd@gmail.com',
        purpose: '1222dsadasd',
        ext: '037787954037787954037787954037787954037787954037787954037787954037787954037787954037787954037787954037787954',
        isDefault: true,
        clientAddressId: 3506,
        countryId: 1,
        jobTitleId: null,
        departmentId: null,
        nationalityId: null,
        firstLanguageId: 616,
        clientDepartment: 'SALES',
        clientJobTitle: 'SUPERVISOR',
        jobTitleName: null,
        departmentName: null,
        nationalityName: null,
        firstLanguageName: null,
        country: null,
        jobTitle: null,
        department: null,
        nationality: null,
        firstLanguage: null,
      },
      defaultContactId: 4103,
    },
    defaultContact: null,
    clientAddresses: null,
    clientAddressContacts: null,
    clientTypes: [
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -6,
        code: 'CTO',
        name: 'CTO',
        displayPosition: 15,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -13,
        code: 'ACP',
        name: 'ACCOUNT PAYABLE',
        displayPosition: 8,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -16,
        code: 'FWD',
        name: 'FORWARDER AGENT',
        displayPosition: 5,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -10,
        code: 'CLO',
        name: 'CO-LOADER',
        displayPosition: 11,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -4,
        code: 'WAH',
        name: '3PL WAREHOUSE',
        displayPosition: 17,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -5,
        code: 'CY',
        name: 'CY',
        displayPosition: 16,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -11,
        code: 'ILC',
        name: 'INLAND CARRIER',
        displayPosition: 10,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -9,
        code: 'CNO',
        name: 'SHIPPER',
        displayPosition: 12,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -7,
        code: 'CFS',
        name: 'CFS',
        displayPosition: 14,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -18,
        code: 'AIL',
        name: 'AIRLINE',
        displayPosition: 3,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -12,
        code: 'NTF',
        name: 'NOTIFY PARTY',
        displayPosition: 9,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -8,
        code: 'CNE',
        name: 'CONSIGNEE',
        displayPosition: 13,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -17,
        code: 'SPL',
        name: 'SHIPPING LINE',
        displayPosition: 4,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -15,
        code: 'CUS',
        name: 'CUSTOMS BROKER',
        displayPosition: 6,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -2,
        code: 'SVP',
        name: 'SERVICE PROVIDER',
        displayPosition: 19,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -3,
        code: 'AGN',
        name: 'SERVICE PROVIDER AGENT',
        displayPosition: 18,
        description: null,
        isSystem: true,
      },
      {
        createdAt: null,
        createdBy: null,
        updatedAt: null,
        updatedBy: null,
        status: 'ACTIVE',
        createdUsername: 'System',
        updatedUsername: 'System',
        id: -14,
        code: 'ACR',
        name: 'ACCOUNT RECEIVABLE',
        displayPosition: 7,
        description: null,
        isSystem: true,
      },
    ],
    apAddress: {
      createdAt: '2026-03-29T10:42:43.358544',
      createdBy: 1,
      updatedAt: '2026-03-30T10:42:02.936746',
      updatedBy: 1,
      status: 'ACTIVE',
      createdUsername: 'Super Admin',
      updatedUsername: 'Super Admin',
      id: 3506,
      code: 'CS002111-ADD',
      name: '223213',
      taxId: null,
      fullAddress: 'DSADASSADSADSAD',
      vnFullAddress: 'DSAD',
      email: null,
      fax: 'dsadas',
      telephone: 'dsada',
      ext: 'dsadas',
      startWorkingHour: null,
      endWorkingHour: null,
      isDefault: true,
      workingDays: [],
      clientId: 3663,
      countryId: 3,
      countryName: null,
      country: null,
      client: null,
      branchAddressCapabilities: null,
      branchAddressCapabilityIds: null,
      defaultContact: null,
      defaultContactId: 4103,
    },
    arAddress: {
      createdAt: '2026-03-29T10:42:43.358544',
      createdBy: 1,
      updatedAt: '2026-03-30T10:42:02.936746',
      updatedBy: 1,
      status: 'ACTIVE',
      createdUsername: 'Super Admin',
      updatedUsername: 'Super Admin',
      id: 3506,
      code: 'CS002111-ADD',
      name: '223213',
      taxId: null,
      fullAddress: 'DSADASSADSADSAD',
      vnFullAddress: 'DSAD',
      email: null,
      fax: 'dsadas',
      telephone: 'dsada',
      ext: 'dsadas',
      startWorkingHour: null,
      endWorkingHour: null,
      isDefault: true,
      workingDays: [],
      clientId: 3663,
      countryId: 3,
      countryName: null,
      country: null,
      client: null,
      branchAddressCapabilities: null,
      branchAddressCapabilityIds: null,
      defaultContact: null,
      defaultContactId: 4103,
    },
    clientSubsidiaryRelationType: null,
  },
]
