// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  create_token: 'Create Token'
  burn_token: 'Burn Token'
  update_metadata: 'Update Metadata'
  close_token_account: 'Close Token Account'
  liquidity_pool: 'Liquidity Pool'
  pool: 'Pool'
  overview: 'Overview'
  create_liquidity: 'Create Liquidity'
  create_token_description: 'Create your meme coin in seconds'
  burn_token_description: 'Burn your token easily'
  update_token_description: 'Modify metadata easily'
  close_account_description: 'Reclaim SOL from token accounts'
  liquidity_pool_description: 'Trade instantly for your token'
  enterprise_grade_token_management_platform: 'Enterprise-grade token management platform'
  key_highlight: 'Launch Your <span>Meme Coin</span> on Solana'
  subtitle: 'New millionaire on the way🚀'
  description: 'Trade meme coin ❌, Create meme coin ✅ '
  getStarted: 'Get Started'
  key_1: 'Create a new token on Solana with custom settings and metadata'
  key_2: 'Token Information'
  key_3: 'Token Name'
  key_4: 'Token Symbol'
  key_5: 'Total Supply'
  key_6: 'Description'
  key_7: 'Enter a brief description of your token...'
  key_8: 'Authority Settings'
  key_9: 'Revoke Freeze Authority'
  key_10: 'Revoke Mint Authority'
  key_11: 'Revoke Update Authority'
  key_12: 'Prevents freezing of token accounts'
  key_13: 'Prevents creating additional tokens'
  key_14: 'Prevents updating token metadata'
  key_15: 'Token Image'
  key_16: 'Upload Token Image (Required)'
  key_17: 'Recommended: 512x512px, Max 5MB. Supported formats: PNG, JPG, GIF, WebP'
  key_18: 'Social Links (Optional)'
  key_19: 'Website'
  key_20: 'Telegram'
  key_21: 'Twitter/X'
  key_22: 'Discord'
  key_23: 'Create Token'
  key_24: 'Update Metadata'
  key_25: 'Update your existing token metadata and settings on Solana'
  key_26: 'Select token to update'
  key_27: 'Token Information'
  key_28: 'Update Token'
  key_29: 'Burn Token'
  key_30: 'Permanently reduce the circulating supply of your fungible tokens'
  key_31: 'Select Token to Burn'
  key_32: 'Select a token...'
  key_33: 'Burn Amount'
  key_34: 'Available balance'
  key_35: 'Burning tokens is irreversible'
  key_36: "The tokens will be permanently removed from circulation and can't be recovered."
  key_37: 'Burn Summary'
  key_38: 'Address'
  key_39: 'Maximum Supply'
  key_40: 'Amount to Burn'
  key_41: 'Remaining Supply'
  key_42: 'REDUCES CIRCULATING SUPPLY'
  key_43: 'SOL Locked(Not Closable)'
  key_44: 'SOL Refund(Closable)'
  key_45: 'Connect Wallet'
  key_46: 'No closable tokens'
  key_47: 'There are no closable tokens in your wallet.'
  key_48: 'Create Liquidity'
  key_49: 'Create a new liquidity pool on Solana with custom settings and metadata'
  key_50: 'Base Amount'
  key_51: 'Quote Amount'
  key_52: 'Initial Price'
  key_53: 'Adaptive Fees'
  key_54: 'Adaptive Fees This pool has Adaptive Fees enabled. As pool volatility increases, so do trading fees — providing increased yields for LPs.'
  key_55: 'Pool'
  key_56: 'View the details of a liquidity pool on Solana'
  key_57: 'No pools found for the selected token'
  key_58: 'Please select a different token or create a new pool.'
  key_59: 'Choose your token to view pools'
  key_60: 'Columns'
  faq: {
    name: 'Name'
    email: 'Email'
    message: 'Message'
    need_help: 'Need Help?'
    still_have_questions: 'Still have'
    still_have_questions_highlight: 'Questions?'
    cant_find_answer: "Can't find the answer you're looking for? Our friendly customer support team is ready to help you."
    contact_support_team: 'Contact Support Team'
    we_will_respond_within_24_hours: "We'll respond within 24 hours"
    how_can_we_help_you: 'How can we help you?'
    common_questions_you_might_have: 'Common Questions You'
    common_questions_you_might_have_description: 'Find quick answers to frequently asked questions about our platform.'
    faq_question: [
      {
        question: 'What can I do with my meme coin?'
        answer: 'Your meme coin can be used in multiple ways: trade it on decentralized exchanges (DEX), hold it as an investment, send it to other wallets, provide liquidity to earn rewards, participate in community governance if enabled, or use it within specific platforms that accept your token.'
      },
      {
        question: 'Where is my meme token listed and how can I view it?'
        answer: 'Your meme token is listed on the Solana blockchain and can be viewed through blockchain explorers like Solscan or Solana Explorer. Once created, you can also list it on decentralized exchanges like Raydium or Jupiter, and track its performance on platforms like DexScreener or Birdeye.'
      },
      {
        question: 'Can I send my meme tokens to other wallets?'
        answer: "Yes! You can easily send your meme tokens to any Solana-compatible wallet address. Simply use your wallet (like Phantom or Solflare), enter the recipient's wallet address, specify the amount of tokens you want to send, and confirm the transaction. A small SOL fee will be required for the transaction."
      },
      {
        question: 'How do I swap my meme tokens for other cryptocurrencies?'
        answer: 'You can swap your meme tokens using decentralized exchanges (DEX) on Solana such as Jupiter, Raydium, or Orca. Connect your wallet, select your meme token and the cryptocurrency you want to receive, enter the amount, review the exchange rate and fees, then confirm the swap. Ensure you have some SOL for transaction fees.'
      },
      {
        question: 'Can I transfer my tokens between different wallets and what are the requirements?'
        answer: "Yes, you can transfer your meme tokens between any Solana-compatible wallets. You'll need the recipient wallet address, sufficient tokens to transfer, and a small amount of SOL (typically 0.000005 SOL) to cover the network transaction fee. Transfers are typically completed within seconds on the Solana network."
      },
    ]
  }
  nav: {
    home: 'Home'
    explore: 'Integration'
    testimonials: 'Testimonials'
    faq: 'FAQ'
  }
  footer: {
    allRightsReserved: 'All rights reserved.'
  }
  localeSwitcher: {
    placeholder: 'Language'
    languages: [
      {
        value: 'en'
        label: 'English'
      },
      {
        value: 'vi'
        label: 'Vietnamese'
      },
      {
        value: 'hi'
        label: 'हिंदी'
      },
      {
        value: 'zh-HK'
        label: '繁體中文'
      },
      {
        value: 'fr'
        label: 'Français'
      },
    ]
  }
  hero: {
    titlePrefix: 'Launch Your'
    titleHighlight: 'Meme Coin'
    titleSuffix: 'on Solana'
    subtitle: 'New millionaire on the way to the moon 🚀'
    description: 'Run after meme coin ❌, Create meme coin ✅ '
    getStarted: 'Get Started'
  }
  integration: {
    title: 'The Brands We Work With'
    description: 'Building strong partnerships with the'
    description_highlight: "world's most influential companies."
    description_suffix: 'Collaborating with enterprises and startups alike to push boundaries, disrupt markets, and achieve groundbreaking results.'
    button: 'Create Your Own Token Now'
  }
  testimonials: {
    title: 'What'
    title_highlight: 'Creators'
    title_suffix: 'Are Saying'
    description: 'Real feedback from meme coin creators on X'
  }
  not_found_page: {
    title: 'Page Not Found'
    title_suffix: 'The page you are looking for has been deleted or does not exist.'
    back_to_home: 'Back to Home'
  }
  layout: {
    title: 'NhatCapDang'
    description: 'Create Meme Coin for Free | NhatCapDang'
    template: '%s | NhatCapDang'
    default: 'Create Meme Coin for Free | NhatCapDang'
    keywords: [
      'create meme coin',
      'how to create a meme coin for free',
      'create meme coin pump fun',
      'launch token solana',
      'solana token creator',
      'meme coin generator',
    ]
    description_large_image: 'Create a meme coin on Solana in minutes. No code. Free tools for token creation, burning, metadata updates, and more.'
  }
  metadata: {
    home: {
      title: 'Launch Your Meme Coin on Solana - Create, Trade & Manage Tokens Free | Nhatcapdang'
      default: 'Launch Your Meme Coin on Solana - Create, Trade & Manage Tokens Free | Nhatcapdang'
      description: 'Create a meme coin on Solana in minutes. No code required. Free tools for token creation, burning, metadata updates, and instant trading. Start today!'
      keywords: [
        'create meme coin',
        'how to create a meme coin for free',
        'create meme coin pump fun',
        'launch token solana',
        'solana token creator',
        'meme coin generator',
        'launch meme coin solana',
        'create meme coin solana',
        'trade meme coin solana',
        'manage meme coin solana',
        'meme coin solana',
        'meme coin solana',
      ]
    }
    overview: {
      title: 'Overview - Personal Token Management Platform'
      description: 'Enterprise-grade token management platform for your meme coin, create, trade and manage tokens free'
      keywords: [
        'overview',
        'token management',
        'create token',
        'burn token',
        'update metadata',
        'close token account',
        'create liquidity',
        'create liquidity pool',
        'create liquidity pool description',
        'base token',
        'quote token',
        'select base token',
        'select quote token',
        'choose base token placeholder',
        'choose quote token placeholder',
        'token amounts',
        'initial price',
        'fee tier',
        'fee tier description',
        'creating liquidity pool',
        'create liquidity pool button',
        'fee tier stable',
        'fee tier less volatile',
        'fee tier most common',
        'fee tier exotic',
        'launch your meme coin in seconds',
        'create token description',
      ]
    }
    create_token: {
      title: 'Create Your Own Meme Coin Now'
      description: 'Create a meme coin on Solana in minutes. No code required. Free tools for token creation, burning, metadata updates, and instant trading. Start today!'
      keywords: [
        'create meme coin',
        'how to create a meme coin for free',
        'create meme coin pump fun',
        'launch token solana',
        'solana token creator',
        'meme coin generator',
        'launch meme coin solana',
        'create meme coin solana',
        'trade meme coin solana',
        'manage meme coin solana',
        'meme coin solana',
        'meme coin solana',
      ]
    }
    update_token: {
      title: 'Update Metadata for Your Meme Coin on Solana'
      description: 'Update metadata for your meme coin on Solana easily on the fly. No code required. Free tools for token creation, burning, metadata updates, and instant trading. Start today!'
      keywords: [
        'update solana token metadata',
        'update solana token info',
        'solana token',
        'solana metadata',
        'solana token metadata update',
        'change image solana token',
        'change name solana token',
        'change description solana token',
        'change symbol solana token',
        'change website solana token',
        'change telegram solana token',
        'change twitter solana token',
        'change discord solana token',
        'change freeze authority solana token',
        'change mint authority solana token',
        'change update authority solana token',
        'change primary sale happened solana token',
        'change seller fee basis points solana token',
        'change creators solana token',
        'change metadata solana token',
      ]
    }
    pool: {
      title: 'Pool Details for Your Meme Coin on Solana'
      description: 'View the details of a liquidity pool on Solana'
      keywords: [
        'view pool details on solana',
        'view pool details description',
        'pool details solana',
        'choose base token',
        'choose quote token',
        'choose base token placeholder',
        'choose quote token placeholder',
        'token amounts',
        'initial price',
        'fee tier',
        'fee tier description',
        'creating liquidity pool',
        'create liquidity pool button',
        'fee tier stable',
        'fee tier less volatile',
        'fee tier most common',
        'fee tier exotic',
        'launch your meme coin in seconds',
        'create token description',
      ]
    }
    close_token_account: {
      title: 'Close Token Account for Your Meme Coin on Solana'
      description: 'Close the token account for your meme coin on Solana'
      keywords: [
        'close token account on solana',
        'close token account',
        'close token account recover sol',
        'close token account receive sol',
        'close token account button',
        'close token account placeholder',
        'close token account placeholder',
        'how to close token account',
        'how to close token account on solana',
        'how to close token account on solana',
      ]
    }
    burn_token: {
      title: 'Burn Token for Your Meme Coin on Solana'
      description: 'Burn your token easily, lose all your tokens forever, increase the value of the remaining tokens'
      keywords: [
        'burn token on solana',
        'how to burn token',
        'burn token button',
        'burn token placeholder',
        'burn token description',
        'burn token on solana',
        'burn token increase value token',
      ]
    }
  }
}
export default messages
